In [1]:
import cv2
import numpy as np

In [2]:
cv2.__version__

'4.5.5'

In [3]:
human=cv2.imread("./data_2/human.jpg")

In [4]:
type(human)

numpy.ndarray

In [5]:
human_copy=human.copy()

In [6]:
# line 2&3 use to dont get error when we close the output window
cv2.imshow('human',human)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
human.shape

(510, 768, 3)

In [8]:
#mask
mask=np.zeros(human.shape[:2], np.uint8) # mask=np.zeros(human.shape[:-1]) that same

In [9]:
# creat dummy array for fetures using
bgd=np.zeros((1,65),np.float64) # creat background
fgd=np.zeros((1,65),np.float64) # creat front background

In [10]:
# how to select region using openv => by using  selectro function 
# thes function help me to find thw w&h for the obj which i need
rect=cv2.selectROI(human)

In [11]:
cv2.imshow('human',rect)
cv2.waitKey(10)
cv2.destroyAllWindows()

In [12]:
x,y,w,h=rect

In [13]:
cv2.rectangle(human_copy,(x,y),(x+w,y+h),(0,0,255),3)

array([[[34, 60, 67],
        [31, 57, 64],
        [29, 54, 64],
        ...,
        [30, 56, 63],
        [32, 55, 63],
        [32, 55, 63]],

       [[34, 60, 67],
        [34, 60, 67],
        [33, 58, 68],
        ...,
        [28, 54, 61],
        [32, 54, 65],
        [32, 55, 63]],

       [[36, 61, 71],
        [35, 60, 70],
        [33, 58, 68],
        ...,
        [28, 53, 63],
        [33, 55, 67],
        [34, 56, 67]],

       ...,

       [[37, 55, 38],
        [38, 56, 39],
        [35, 54, 37],
        ...,
        [54, 99, 82],
        [51, 95, 78],
        [46, 90, 73]],

       [[36, 55, 36],
        [37, 56, 37],
        [35, 55, 36],
        ...,
        [53, 98, 82],
        [50, 95, 79],
        [46, 91, 75]],

       [[35, 54, 35],
        [37, 56, 37],
        [35, 55, 36],
        ...,
        [50, 97, 81],
        [48, 93, 77],
        [43, 88, 72]]], dtype=uint8)

In [14]:
cv2.imwrite("Human_ROI.png",human_copy)

True

In [15]:
# algorithm grabcut we cut original image according the rect image 
#5==num of iteration
cv2.grabCut(human,mask,rect,bgd,fgd,5,cv2.GC_INIT_WITH_RECT)
# this fun return 3 valuse one respect bgd,one respect values we find by ROI and the last one respect human

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[1.90178714e-01, 1.50806323e-01, 1.19742364e-01, 2.07970279e-01,
         3.31302320e-01, 3.49409454e+01, 8.30500442e+01, 6.43681204e+01,
         5.40826401e+01, 9.87794752e+01, 1.03235858e+02, 2.88135819e+01,
         5.01946329e+01, 4.52922113e+01, 3.67221453e+01, 6.38394593e+01,
         7.91742778e+01, 4.50461372e+01, 1.00305490e+02, 8.18609000e+01,
         6.17882248e+01, 4.03773575e+01, 3.97164064e+01, 4.03773575e+01,
         6.18321307e+01, 6.11120555e+01, 3.97164064e+01, 6.11120555e+01,
         6.94877614e+01, 2.34287260e+02, 2.36728369e+02, 2.27525430e+02,
         2.36728369e+02, 3.15241432e+02, 1.76477313e+02, 2.27525430e+02,
         1.76477313e+02, 3.83222126e+02, 7.44651650e+01, 7.54763145e+01,
         5.25574380e+01, 7.54763145e+01, 1.5

In [16]:
mask.shape

(510, 768)

In [17]:
mask.min(),mask.max()

(0, 3)

In [18]:
#the most of valuse is go to be 1.14 ==>white so background 0 mask=1 ,rect=2 
mask.std()

1.1450926946622932

In [19]:
# creat mask2 we get 3values from grabcut 0,1,2
mask2 = np.where((mask == 2 ) | (mask == 0), 0, 1).astype("uint8")#last 0.1 is refer to white if true else black 
cv2.imwrite("mask.png", mask*80)
cv2.imwrite("mask2.png", mask2*255)

True

In [20]:
np.unique(mask)

array([0, 2, 3], dtype=uint8)

In [21]:
np.unique(mask2)

array([0, 1], dtype=uint8)

In [22]:
mask.ndim,mask2.ndim

(2, 2)

In [23]:
#inference on original data (image),mask2 return just human so we take it
human = human * mask2[:,:,np.newaxis]
cv2.imwrite("result.png", human)

True

## Videos 


## Cars

In [2]:
haar_cascae_car="./data_2//xml/haarcascade_car.xml"

In [3]:
car_class = cv2.CascadeClassifier (haar_cascae_car)

In [4]:
# read cars video using fun in cv => vieo capture
cap= cv2.VideoCapture("./data_2/cars.avi")

In [5]:
count=0
while cap.isOpened():
    count+=1
    if count  % 20==0:# every 20 milliseconde        
        ret,frame=cap.read()        
        gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY) # convert each frame to gray
        cars=car_class.detectMultiScale(gray, 1.1, 3)#calssification , detect for every frame
        
        for(x,y,w,h) in cars:
            cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),3)          
            cv2.putText(frame,"car",(x,y),cv2.FONT_HERSHEY_SIMPLEX ,0.5, (0,0,255))  # fun control the put text like the type of font the coordinate ,...etc // note we take this argument from document
        cv2.imshow("cars",frame)
    if cv2.waitKey(10) & 0xFF == ord("q"):  # waitKey    
        break 
cap.release()
cv2.destroyAllWindows()
            